Fix mac builds due to unguarded-availability error
Just bump our required base version up, as developing Android already
effectively requires 10.13, and these tools won't be distributed to
end-user developers (like fastboot/adb/aapt/etc are).

toolchain/make/src/file.c:898:9: error: 'clock_gettime' is only available on macOS 10.12 or newer [-Wunguarded-availability]

Test: build
Change-Id: I5aef02e9fc6f91fd04381b8895bf656675ccac51